"""
Django settings for chatweb project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&%e6-9(j3+fkyadmq+k0*7-1(4&oh%e4&7wt*5urim4f7gn)74"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "simpleui",

    #官方自带
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    #第三方应用
    # 'django_elasticsearch_dsl',

    #我的应用
    "chatweb",
    "accounts",
    "index",
    "userspace",
    "post_search",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "chatweb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR/"templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "chatweb.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#mysql
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME":  "chatdata",     #数据库名
        "HOST":  "127.0.0.1",  #端口
        "PORT": 3306,          #数据库ip
        "USER": "root",        #账号
        "PASSWORD": "123456",    #密码
        'POOL_OPTIONS':{            #pool表示数据库连接池配置，主要为了节省连接数据库的开销，临时存储数据库连接对象
            'POOL_SIZE':10,         #默认情况下，打开的数据库连接对象的数量 [1,2,3,4,5,6,7,8,9,10]
            'MAX_OVERFLOW':30,      #负载情况下，允许溢出的连接数量  [11,12,13,14,15,16,17,18,19,20]
        },
        'OPTIONS':{
            'charset':'utf8mb4',#支持表情符号
        },
    }
}


# ELASTICSEARCH_DSL = {
#     'default': {
#         'hosts':['http://localhost:9200'],
#         'timeout': 30,
#         # 可选：设置默认索引前缀
#         # 'index_prefix': 'myapp',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


AUTH_USER_MODEL = 'index.User'  #自己定义的用户表单

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"  # 访问静态资源的URL前缀
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # 项目级静态目录
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')    #静态文件收集
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CSRF_COOKIE_HTTPONLY = False

MEDIA_ROOT = os.path.join(BASE_DIR, "media")  # 项目根目录下的media文件夹
MEDIA_URL = '/media/'  # 访问媒体资源的URL前缀

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # 默认后端
    # 其他自定义后端（如有）
    'accounts.backends.EmailBackend',
]

# 确保启用数据库会话存储（默认方式）
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

LOGIN_REDIRECT_URL = 'chat:index' #默认的登录成功跳转

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}