# Generated by Django 5.1.7 on 2025-05-29 07:30

import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="static/images/申鹤.jpg",
                null=True,
                upload_to=index.models.user_avatar_path,
                verbose_name="头像",
            ),
        ),
    ]
