# Generated by Django 5.1.7 on 2025-05-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_alter_user_avatar"),
    ]

    operations = []
