# Generated by Django 5.1.7 on 2025-05-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0003_auto_20250529_1718"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
