# Generated by Django 5.1.7 on 2025-05-30 05:52

import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatar/default/申鹤.jpg",
                null=True,
                upload_to=index.models.user_avatar_path,
                verbose_name="头像",
            ),
        ),
    ]
